package com.example.demo.platform.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SwaggerConfig {
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("MARLO API Documentation")
                        .version("1.0.0")
                        .description(
                                "MARLO is an online platform assisting AICCRA project in their strategic results-based program planning and reporting of research clusters. " +
                                "It covers the cluster cycle from planning to reporting and learning. Reports generated by the system support outcome-focused " +
                                "programmatic reporting with additional synthesis at the flagship and cross-cutting levels. " +
                                "This RESTful API provides comprehensive endpoints for managing project innovations, tracking development phases, " +
                                "monitoring partnerships, and facilitating data-driven decision making across research initiatives."));
    }
}
