package com.example.demo.modules.greeting.domain.model;

import com.example.demo.sharedkernel.domain.Message;

import java.util.Objects;

/**
 * Value object that represents the greeting generated by the domain.
 */
public record Greeting(String message) implements Message {
    public Greeting {
        Objects.requireNonNull(message, "message must not be null");
    }

    @Override
    public String getMessage() {
        return message;
    }
}
